# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
arr_1d = np.array([2, 6, 7, 3])
arr_1d

array([2, 6, 7, 3])

In [5]:
# Create a 2-dimensional NumPy array using np.array()
arr_2d = np.array([[1,3,5], [6,9,8]])
arr_2d

array([[1, 3, 5],
       [6, 9, 8]])

In [6]:
# Create a 3-dimensional Numpy array using np.array()
arr_3d = np.array([[[1,2,3], [5,7,9], [2,5,6]]])
arr_3d

array([[[1, 2, 3],
        [5, 7, 9],
        [2, 5, 6]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [8]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
print("Shape:", arr_1d.shape)
print("size of arr: ", arr_1d.size)
print("dimnesion: ", arr_1d.ndim)
print("datatype is : ", arr_1d.dtype)
print("type:", type(arr_1d))

Shape: (4,)
size of arr:  4
dimnesion:  1
datatype is :  int64
type: <class 'numpy.ndarray'>


In [9]:
# Attributes of 2-dimensional array
print("Shape:", arr_2d.shape)
print("size of arr: ", arr_2d.size)
print("dimnesion: ", arr_2d.ndim)
print("datatype is : ", arr_2d.dtype)
print("type:", type(arr_2d))

Shape: (2, 3)
size of arr:  6
dimnesion:  2
datatype is :  int64
type: <class 'numpy.ndarray'>


In [10]:
# Attributes of 3-dimensional array
print("Shape:", arr_3d.shape)
print("size of arr: ", arr_3d.size)
print("dimnesion: ", arr_3d.ndim)
print("datatype is : ", arr_3d.dtype)
print("type:", type(arr_3d))

Shape: (1, 3, 3)
size of arr:  9
dimnesion:  3
datatype is :  int64
type: <class 'numpy.ndarray'>


In [12]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
data1 = pd.DataFrame(arr_2d)
data1

0  1  2
0  1  3  5
1  6  9  8

In [13]:
# Create an array of shape (10, 2) with only ones
ones_arr = np.ones((10,2))
ones_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_arr = np.zeros((7,2,3))
zeros_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
# Create an array within a range of 0 and 100 with step 3
range_arr = np.arange(0,100,3)
range_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [16]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_arr = np.random.randint(0,10, size=(7,2))
random_arr

array([[2, 0],
       [2, 0],
       [7, 3],
       [3, 1],
       [9, 9],
       [2, 9],
       [2, 0]])

In [17]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
randm_flot_arr = np.random.random((3,5))
randm_flot_arr

array([[0.70648487, 0.74036182, 0.29632275, 0.85087997, 0.1007787 ],
       [0.9466237 , 0.94565489, 0.92324307, 0.50675885, 0.36434403],
       [0.22986251, 0.0070983 , 0.45538002, 0.93223477, 0.41485874]])

In [18]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
new_arr = np.random.randint(0,10, size=(4,6))
new_arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [19]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
new_arr2 = np.random.randint(1,10, size=(3,7))
new_arr2

# Find the unique numbers in the array you just created
np.unique(new_arr2)

array([1, 2, 3, 4, 5, 7, 9])

In [20]:
# Find the 0'th index of the latest array you created
new_arr2[0]

array([9, 1, 3, 7, 4, 9, 3])

In [21]:
# Get the first 2 rows of latest array you created
new_arr2[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [22]:
# Get the first 2 values of the first 2 rows of the latest array
new_arr2[:2, :2]

array([[9, 1],
       [5, 3]])

In [23]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_arr2 = np.random.randint(0,10, size=(3,5))
ones_arr2 = np.ones((3,5))
random_arr2, ones_arr2

(array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [26]:
# Add the two arrays together
random_arr2 + ones_arr2

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [27]:
# Create another array of ones of shape (5, 3)
new_ones_arr = np.ones((5,3))
new_ones_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
ones_arr2.shape

(3, 5)

In [28]:
new_ones_arr.shape

(5, 3)

In [30]:
# Try add the array of ones and the other most recent array together
ones_arr2 + new_ones_arr

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [31]:
# Create another array of ones of shape (3, 5)
new_arr_ones = np.ones((3,5))
new_arr_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
# Subtract the new array of ones from the other most recent array
new_arr_ones - ones_arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
# Multiply the ones array with the latest array
subtracted = new_arr_ones * ones_arr2
subtracted

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
random_arr2

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [39]:
# Take the latest array to the power of 2 using '**'
random_arr2 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [41]:
# Do the same thing with np.square()
np.square(random_arr2)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [42]:
# Find the mean of the latest array using np.mean()
np.mean(random_arr2)

3.8666666666666667

In [43]:
# Find the maximum of the latest array using np.max()
np.max(random_arr2)

9

In [44]:
# Find the minimum of the latest array using np.min()
np.min(random_arr2)

0

In [45]:
# Find the standard deviation of the latest array
std = np.std(random_arr2)
std

2.578543947441829

In [46]:
# Find the variance of the latest array
var = np.var(random_arr2)
var

6.648888888888889

In [48]:
random_arr2.shape

(3, 5)

In [47]:
# Reshape the latest array to (3, 5, 1)
np.reshape(random_arr2, (3,5,1))

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [49]:
# Transpose the latest array
random_arr2.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

In [50]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arri = np.random.randint(0,10, size=(3,3))
arrj = np.random.randint(0,10, size=(3,2))
arri, arrj

(array([[9, 1, 9],
        [3, 7, 6],
        [8, 7, 4]]),
 array([[1, 4],
        [7, 9],
        [8, 8]]))

In [55]:
# Perform a dot product on the two newest arrays you created
np.dot(arri, arrj)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [52]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
int_arr1 = np.random.randint(0, 10, size=(4,3))
int_arr2 = np.random.randint(0, 10, size=(4,3))

In [54]:
# Perform a dot product on the two newest arrays you created
np.dot(int_arr2, int_arr2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [56]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(int_arr1.T, int_arr2)

array([[128,  90, 128],
       [184,  91, 151],
       [ 42,  14,  40]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [57]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr4 = np.random.randint(0,10, size=(3,3))
arr5 = np.random.randint(0,10, size=(3,3))

In [58]:
# Compare the two arrays with '>'
arr4 > arr5

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [59]:
# Compare the two arrays with '>='
arr4 >= arr5

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [60]:
# Find which elements of the first array are greater than 7
arr4 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [61]:
# Which parts of each array are equal? (try using '==')
arr4 == arr5

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [62]:
# Sort one of the arrays you just created in ascending order
arr4.sort()
arr4

array([[6, 6, 7],
       [2, 4, 7],
       [0, 2, 5]])

In [63]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr4)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [64]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr5)

5

In [65]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr5)

3

In [66]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr5, axis=1)

array([1, 2, 2])

In [67]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr5, axis=0)

array([1, 0, 0])

In [68]:
# Create an array of normally distributed random numbers
np.random.randn(2,4)

array([[-0.61487576,  0.33289244, -1.38071702, -0.28080629],
       [-0.05981726,  0.96117377,  1.79428084,  0.58068954]])

In [69]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.